# Generated by Django 5.2.8 on 2025-12-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(related_name='owners', through='project_first_app.Ownership', through_fields=('id_owner', 'id_car'), to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='id_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', to='project_first_app.carowner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_ownerships', to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='project_first_app.carowner'),
        ),
    ]
